<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="Moq" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\UMonsPlanning.Pronote\UMonsPlanning.Pronote.csproj" />
    <ProjectReference Include="..\..\src\UMonsPlanning.Backend\UMonsPlanning.Backend.csproj" />
  </ItemGroup>

</Project>
